# This is a basic workflow to help you get started with Actions

name: build-iso

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Check out code
        uses: actions/checkout@v3
      - name: create docker image
        run: docker build -t nix -f .github/workflows/Dockerfile .
      - name: build iso
        run: | 
          docker run -v $PWD/out:/out nix "bash .github/workflows/build-iso.sh \
            nix build .#iso --extra-experimental-features nix-command --extra-experimental-features flakes \
            mkdir -p /out \
            cp result/iso/*.iso /out"
      - name: iso artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: out/*.iso
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: Release snapshot
        id: release-snapshot
        uses: ncipollo/release-action@v1
        with:
          artifacts: out/*.iso
          tag: ${{ steps.date.outputs.date }}
          commit: main
