# This is a basic workflow to help you get started with Actions

name: build-iso

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write 
      attestations: write


    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      # - name: Log in to the Container registry
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: build iso
      #   run: | 
      #     docker run -v $PWD:/dotfiles -u 1001 ghcr.io/eli-sauvage/nixos-with-node bash -c \
      #       "nix build .#iso --extra-experimental-features nix-command --extra-experimental-features flakes"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build .#nixosConfigurations.iso.config.system.build.isoImage
      - name: iso artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: result/iso/*.iso
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: Release snapshot
        id: release-snapshot
        uses: ncipollo/release-action@v1
        with:
          artifacts: result/iso/*.iso
          tag: ${{ steps.date.outputs.date }}
          commit: main
