# This is a basic workflow to help you get started with Actions

name: build-iso

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write 

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build .#nixosConfigurations.live-iso-chromebook.config.system.build.isoImage
      - name: iso artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: result/iso/nixos.iso.zst
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
      - name: Release snapshot
        id: release-snapshot
        uses: ncipollo/release-action@v1
        with:
          artifacts: result/iso/nixos.iso.zst
          tag: ${{ steps.date.outputs.date }}
          commit: main
